# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62db872f48c72b702a5488a60e6392640dce6ec5f7ba1cf14315d0d0c1f7f273d0eeb3ac7ffdf1ee60b8ca965e7f6463581961447d8d0ee6ad8609dbf0007425

test:
  secret_key_base: ec6632514f8fb1b29c2b8e46d6f70cc6af0d4c925fb0c4f5f82f853d82ccfe70c3ac8190efc5f87b293e157de01b1c6957be4279321e721561bddbb7b93cd290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
